apiVersion: skaffold/v4beta13
kind: Config

metadata:
  name: v0



build:

  tagPolicy:
    sha256: {}

  platforms:
    - linux/amd64 

  artifacts:
    - image: 329599656829.dkr.ecr.ap-southeast-1.amazonaws.com/template
      context: sandbox/template
      docker:
        dockerfile: dockerfile

    - image: 329599656829.dkr.ecr.ap-southeast-1.amazonaws.com/agent
      context: sandbox/agent
      docker:
        dockerfile: dockerfile

    - image: 329599656829.dkr.ecr.ap-southeast-1.amazonaws.com/sandbox
      context: sandbox/server
      docker:
        dockerfile: dockerfile

    - image: 329599656829.dkr.ecr.ap-southeast-1.amazonaws.com/router
      context: sandbox/router
      docker:
        dockerfile: dockerfile

    - image: 329599656829.dkr.ecr.ap-southeast-1.amazonaws.com/ai-orchestrator
      context: ai
      docker:
        dockerfile: dockerfile
    
    - image: 329599656829.dkr.ecr.ap-southeast-1.amazonaws.com/auth
      context: auth
      docker:
        dockerfile: dockerfile

    - image: 329599656829.dkr.ecr.ap-southeast-1.amazonaws.com/sync
      context: sandbox/sync-agent
      docker:
        dockerfile: dockerfile

manifests:
  rawYaml:
    - k8s/ai-deployment.yml
    - k8s/ai-service.yml
    - k8s/ingress.yml
    - k8s/rbac.yml
    - k8s/router-deployment.yml
    - k8s/router-service.yml
    - k8s/sandbox-server-deployment.yml
    - k8s/sandbox-server-service.yml
    - k8s/secrets.yml
    - k8s/auth-deployment.yml
    - k8s/auth-service.yml


