apiVersion: skaffold/v4beta13
kind: Config

metadata:
  name: v0



build:

  tagPolicy:
    sha256: {}

  artifacts:
    - image: template
      context: sandbox-microservice/template
      docker:
        dockerfile: dockerfile

    - image: agent
      context: sandbox-microservice/agent
      docker:
        dockerfile: dockerfile

    - image: sandbox
      context: sandbox-microservice/server
      docker:
        dockerfile: dockerfile

    - image: router
      context: sandbox-microservice/router
      docker:
        dockerfile: dockerfile

    - image: ai-orchestrator
      context: ai-microservice
      docker:
        dockerfile: dockerfile
    
    - image: auth
      context: auth-microservice
      docker:
        dockerfile: dockerfile

    - image: sync
      context: sandbox-microservice/sync-agent
      docker:
        dockerfile: dockerfile

manifests:
  rawYaml:
    - kubernetes/ai-deployment.yml
    - kubernetes/ai-service.yml
    - kubernetes/ingress.yml
    - kubernetes/rbac.yml
    - kubernetes/router-deployment.yml
    - kubernetes/router-service.yml
    - kubernetes/sandbox-server-deployment.yml
    - kubernetes/sandbox-server-service.yml
    - kubernetes/secrets.yml
    - kubernetes/auth-deployment.yml
    - kubernetes/auth-service.yml


